config/routes.rb
  resources :incisos

  resources :reportes_a_fecha do
    member do
      post 'imprimir_formulario'
    end
    collection do
      get 'traer_items_stock'
    end
  end

  resources :bienes_de_consumo do
    collection do
      get 'autocomplete_bien_de_consumo_nombre_traer_todos_los_items'
      get 'traer_items_de_la_clase'
      get 'traer_item_por_id'
      get 'traer_todos_los_items'
      get 'traer_vista_de_categoria'
      get 'traer_clases_con_codigo_de_bien_existente'
      get 'traer_clases_con_nombre_de_bien_de_consumo_similar'
      get 'ver_items_dados_de_baja'
      get 'existen_stocks_minimos_superados'
      post 'imprimir_listado_de_items'
      post 'traer_costo_de_bien_de_consumo'
    end

    # resources :areas  do
    #   resources :items_stock do
    #     #post 'imprimir_formulario_stock_total_por_bien_y_area'
    #   end
    #end
  end


  get 'bienes_de_consumo/:bien_de_consumo_id/traer_vista_dar_de_baja_y_reemplazar/',
                                to: 'bienes_de_consumo#traer_vista_dar_de_baja_y_reemplazar',
                                as: 'traer_vista_dar_de_baja_y_reemplazar_bienes_de_consumo'

  put 'bienes_de_consumo/:bien_de_consumo_id/dar_de_baja_y_reemplazar_bienes_de_consumo/',
                                to: 'bienes_de_consumo#dar_de_baja_y_reemplazar_bienes_de_consumo',
                                as: 'dar_de_baja_y_reemplazar_bienes_de_consumo'

  resources :personas

  resources :recepciones_de_bien_de_consumo do
      collection do
        get 'ver_rechazadas'
        get 'traer_documentos_con_numero_existente'
      end
      resources :bienes_de_consumo_de_recepcion , only: [:index, :new, :create, :destroy, :show]
  end

  get 'recepciones_de_bien_de_consumo/enviar_a_evaluar/:id',
                                        :to => 'recepciones_de_bien_de_consumo#enviar_a_evaluar',
                                        :as => 'enviar_a_evaluar_recepciones_de_bien_de_consumo'


  post 'bienes_de_consumo_de_recepcion/obtener_nombre_de_bien_de_consumo',
                                        :to => 'bienes_de_consumo_de_recepcion#obtener_nombre_de_bien_de_consumo',
                                        :as => 'obtener_nombre_bien_de_consumo_bienes_de_consumo_de_recepcion'

  post 'bienes_de_consumo_de_recepcion/obtener_codigo_de_bien_de_consumo',
                                        :to => 'bienes_de_consumo_de_recepcion#obtener_codigo_de_bien_de_consumo',
                                        :as => 'obtener_codigo_bien_de_consumo_bienes_de_consumo_de_recepcion'

  delete 'recepciones_de_bien_de_consumo/:recepcion_de_bien_de_consumo_id/eliminar_bien_de_recepcion/:bien_de_consumo_id' => 'recepciones_de_bien_de_consumo#eliminar_bien_de_recepcion',
                                        as: 'eliminar_bienes_de_recepcion_recepciones_de_bien_de_consumo'

  post 'recepciones_de_bien_de_consumo/pegar_campo_descripcion_provisoria', :to => 'recepciones_de_bien_de_consumo#pegar_campo_descripcion_provisoria'

  delete 'recepciones_de_bien_de_consumo/:recepcion_de_bien_de_consumo_id/eliminar_documento_secundario/:documento_secundario_id' => 'recepciones_de_bien_de_consumo#eliminar_documento_secundario',
                                        as: 'eliminar_documento_secundario_recepciones_de_bien_de_consumo'

  resources :transferencias do
    collection do
      get 'nueva_transferencia'
      post 'crear_transferencia'
    end
  end

  get 'transferencias/:recepcion_id/nueva_transferencia_desde_recepcion/',
                                                            to: 'transferencias#nueva_transferencia_desde_recepcion',
                                                            as: 'nueva_transferencia_desde_recepcion_transferencias'

  resources :recepciones_de_bien_de_consumo_en_stock, only: [:index , :show]  do
      get 'imprimir_detalle_recepcion'
      collection do
        get 'autocomplete_documento_principal_nombre'
        get 'traer_recepciones_por_doc_principal'
        get 'ver_recepciones_finalizadas_por_bien_de_consumo_y_fecha'
        get 'traer_recepciones_por_bien_y_fecha'
        get 'ver_recepciones_finalizadas_por_fecha'
        get 'traer_recepciones_finalizadas_por_fecha'
        get 'ver_recepciones_finalizadas_por_fecha_por_recepcion'
        get 'traer_recepciones_finalizadas_por_fecha_por_recepcion'
      end
  end

  get 'recepciones_de_bien_de_consumo_en_stock/documento_principal/:documento_principal/imprimir_formulario_recepciones_por_documento_principal/',
                                                            to: 'recepciones_de_bien_de_consumo_en_stock#imprimir_formulario_recepciones_por_documento_principal',
                                                            as: 'imprimir_formulario_recepciones_por_documento_principal'


  post 'recepciones_de_bien_de_consumo_en_stock/bien_de_consumo/:bien_de_consumo_id/fecha_inicio/:fecha_inicio/fecha_fin/:fecha_fin/imprimir_formulario_recepciones_finalizadas_por_bien_y_fecha/',
                                                            to: 'recepciones_de_bien_de_consumo_en_stock#imprimir_formulario_recepciones_finalizadas_por_bien_y_fecha',
                                                            as: 'imprimir_formulario_recepciones_finalizadas_por_bien_y_fecha'

  post 'recepciones_de_bien_de_consumo_en_stock/fecha_inicio/:fecha_inicio/fecha_fin/:fecha_fin/imprimir_formulario_recepciones_finalizadas_por_fecha/',
                                                            to: 'recepciones_de_bien_de_consumo_en_stock#imprimir_formulario_recepciones_finalizadas_por_fecha',
                                                            as: 'imprimir_formulario_recepciones_finalizadas_por_fecha'

  get 'recepciones_de_bien_de_consumo_en_stock/fecha_inicio/:fecha_inicio/fecha_fin/:fecha_fin/imprimir_formulario_recepciones_finalizadas_por_fecha_por_recepcion/',
                                                            to: 'recepciones_de_bien_de_consumo_en_stock#imprimir_formulario_recepciones_finalizadas_por_fecha_por_recepcion',
                                                            as: 'imprimir_formulario_recepciones_finalizadas_por_fecha_por_recepcion'


  resources :recepciones_de_bien_de_consumo_consumidas, only: [:index , :show]
  resources :depositos
  resources :items_stock , only: [:index, :new ] do
    collection do
      post'ingresar_bienes_a_stock_manualmente'
       get 'guardar_stock_a_fecha'
       get 'traer_todos_los_items_stock'
       get 'traer_items_stock_por_bien_y_area'
       get 'traer_items_stock_por_fecha_bien_y_area_suministro'
       get 'traer_items_stock_minimo_superado'
       get 'traer_items_stock_minimo_superado_por_bien_y_area'
       get 'traer_datos_de_clase_y_bien'
       get 'ver_stock_minimo_superado'
       get 'ver_stock_con_subtotal_por_pp'
       get 'autocomplete_bien_de_consumo_nombre'
       get 'autocomplete_area_nombre'
       post 'imprimir_formulario_stock_total_todos_los_bienes'
      post 'traer_cantidad_en_stock_en_suministro'
      post 'imprimir_formulario_stock_faltante'
     end
  end



  post 'items_stock/area_id/(:area_id)/bien_id/(:bien_id)/partida_parcial/(:partida_parcial)/fecha_inicio/(:fecha_inicio)/fecha_fin/(:fecha_fin)/imprimir_formulario_stock_total_por_bien_y_area/',
                                                            to: 'items_stock#imprimir_formulario_stock_total_por_bien_y_area',
                                                            as: 'imprimir_formulario_stock_total_por_bien_y_area'

  post 'items_stock/area_id/(:area_id)/bien_id/(:bien_id)/imprimir_formulario_stock_faltante/',
                                                            to: 'items_stock#imprimir_formulario_stock_faltante',
                                                            as: 'imprimir_formulario_stock_faltante'

  post 'items_stock/imprimir_formulario_stock_total_con_subtotal_por_pp/', to: 'items_stock#imprimir_formulario_stock_total_con_subtotal_por_pp',
                                                                          as: 'imprimir_formulario_stock_total_con_subtotal_por_pp'


  post 'recepciones_de_bienes_de_consumo_en_stock/:recepcion_de_bien_de_consumo_id/items_stock/imprimir_formulario/',
                                                            to: 'items_stock#imprimir_formulario',
                                                            as: 'imprimir_items_stock_recepciones_de_bien_de_consumo_en_stock'


  post 'transferencias/imprimir_formulario/:transferencia_id',  to: 'transferencias#imprimir_formulario',
                                                                    as: 'imprimir_formulario_transferencias'


  get 'items_stock/:recepcion_id/ver_ingresar_a_stock/',  to: 'items_stock#ver_ingresar_a_stock',
                                                          as: 'ver_ingresar_a_stock_items_stock'

  resources :areas do
    resources :depositos , only: [:new, :destroy]
  end


  resources :consumos_directo do
    collection do
      post 'obtener_item_para_agregar_a_recepcion_by_id'
      get 'autocomplete_obra_proyecto_descripcion'
      get 'nuevo_consumo'
      get 'ver_dados_de_baja'
      post 'crear_consumo'
      post 'obtener_nombre_de_bien_de_consumo'
      post 'obtener_nombre_y_stock_de_bien_de_consumo_por_id_y_deposito'
      post 'obtener_responsable_de_area'
      get 'ver_consumos_por_codigo_destino_fecha'
      get 'ver_consumos_y_transferencias_por_nombre_y_fecha'
      get 'traer_consumos_y_transferencias_por_nombre_y_fecha'
      get 'traer_consumos_por_codigo_destino_y_fecha'
      get 'traer_consumos_por_obra_proyecto_destino_y_fecha'
      get 'ver_consumos_por_obra_proyecto_y_fecha'
      get 'traer_consumos_por_partida_parcial_destino_y_fecha'
      get 'ver_consumos_por_partida_parcial_destino_fecha'
      get 'ver_consumos_por_fecha_destino_y_clase'
      get 'traer_consumos_por_fecha_destino_y_clase'
    end
  end

app/models/transferencia.rb
class Transferencia < ActiveRecord::Base
	ESTADOS = { :ACTIVO => 1, :ANULADO => 2 }
  	belongs_to :area
  	belongs_to :deposito    
  
  	has_many :bienes_de_consumo_para_transferir
  	has_one :recepcion_de_bien_de_consumo
  	has_one :recepcion_para_transf

  	validates :fecha, presence: true
  	validates :area, presence: true    
  	validates :deposito_id, presence: true    
end

app/helpers/transferencias_helper.rb
module TransferenciasHelper
end

app/views/transferencias/_form.html.erb
<%= form_for(@transferencia) do |f| %>
  <% if @transferencia.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transferencia.errors.count, "error") %> encontrados en la transferencia. No sera generada:</h2>

      <ul>
      <% @transferencia.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fecha %><br>
    <%= f.text_field :fecha %>
  </div>

   <div class="field">
      <%= f.label :area, "Area destino"%><br /> 
      <%= f.collection_select :area_id, @areas, :id, :nombre, :prompt => "seleccione" %>            
  </div>

  <div class="field">
    <%= f.label :responsable %> <br /> 
    <%= text_field_tag :responsable, nil, readonly: true%>  
  </div> 

  <div class="field">
    <%= f.label :deposito %> <br />     
    <%= f.grouped_collection_select("deposito_id", @areas, "depositos", "nombre", "id", "nombre", :include_blank => " Seleccione un deposito...") %>
  </div> 

  <div>
    <%= hidden_field(:recepcion_de_bien_de_consumo, :id)  %>
  </div>

  <div class="panel panel-default">
   <div class="panel-heading">Bienes de consumo</div>
  <table class="table">
  <thead>
  <tr>
    <th>Clase</th>
    <th>Nombre</th>
    <th>Codigo</th>
    <th>Cantidad</th>
    <th>Costo</th>    
  </tr>
  </thead>
  <tbody>
  <% if @recepcion_de_bien_de_consumo.bienes_de_consumo_de_recepcion.any? %>
      <% @recepcion_de_bien_de_consumo.bienes_de_consumo_de_recepcion.each do |bcr| %>
      <tr>        
        <% if bcr.bien_de_consumo %>
            <td><%= bcr.bien_de_consumo.clase.nombre %> </td>
            <td><%= bcr.bien_de_consumo.nombre %> </td>
            <td><%= obtener_codigo_completo_bien_de_consumo(bcr.bien_de_consumo.nombre) %> </td>
            <td><%= bcr.cantidad %> </td>
            <td><%= bcr.costo %> </td>                        
        <% end %> 
      </tr>            
      <%end%>
  <% else %>
      <tr>        
        <td></td>
        <td></td>
      </tr>    
  <% end %>      
  </tbody>
  </table>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transferencias/_form_nueva_transferencia.html.erb
<%= form_for(@transferencia, 
             url:   crear_transferencia_transferencias_path, 
             html: { method: "post",  :id => "nueva_transferencia"} ) do |f| %>
  <% if @transferencia.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transferencia.errors.count, "error") %> prohibited this consumo from being saved:</h2>
      <ul>
      <% @transferencia.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field" id="impresion">        
  </div> 

  <div class="field">    
    <%= f.label :fecha %><br />
    <%= f.text_field :fecha %>  
  </div> 

  <div class="field">
      <%= label :area , "Area origen" %><br /> 
      <%= collection_select(:transferencia_area_origen, "area_id", @areas, "id", "nombre", :include_blank => "Seleccione un area...") %>
  </div>

  <div class="field">
    <%= label :deposito, "Deposito origen" %> <br />     
    <%= grouped_collection_select(:transferencia_deposito_origen, :deposito_id, @areas, :depositos, :nombre, :id, :nombre, :include_blank => " Seleccione un deposito...") %>
  </div>         
  
  <div class="field">
    <%= f.label :responsable %> <br /> 
    <%= text_field_tag :responsable, nil, readonly: true%>  
  </div> 


 <div class="row">
  <div class="col-md-3">      
    <h3> Buscar por nombre </h3>   
    <div class="field">
         <%= f.label :nombre%><br>  
      </div>   
      <div class="field">
          <%= autocomplete_field_tag 'transferencia_nombre', '', autocomplete_bien_de_consumo_nombre_items_stock_path , :size => 75, :update_elements => {} %>
      </div>  
  </div>  
  <div class="col-md-3">      
      <h3> Ingresar codigo </h3>   
    <div class="field">
      <%= f.label :codigo%><br>
      <%= text_field_tag :codigo %>
    </div>  
    <div class="field">
        <input type="button" value="Traer Bien de Consumo" class="" id="traer_bien_de_consumo_y_cantidad_stock_tranferencia">            
    </div>    
  </div>

  <div class="col-md-3">        
    <h3> Seleccionar arbol </h3>            
      <div class="field"> 
      <%= label_tag :clase, "Clase" %><br>
      <%= collection_select(:categoria, "clase_id", Clase.joins(:partida_parcial => [:partida_principal]).where("clases.fecha_de_baja IS NULL").order("partidas_principales.codigo").order("partidas_parciales.codigo").order("clases.codigo"), "id", "combinar_codigo_nombre", :include_blank => "Seleccione...") %> 
           
      </div>    
      <div class="field">     
        <%= label_tag :bien_de_consumo, "Bien de consumo" %><br>
        <%= grouped_collection_select(:transferencias, :bien_de_consumo_id, Clase.where("fecha_de_baja IS NULL"), :bienes_de_consumo, :nombre, :id, :nombre, :include_blank => " Seleccione...") %>
      </div>
  </div>      
</div>        

   <div class="field">
    <%= f.label :cantidad_stock, "Cantidad en stock" %><br>
    <%= text_field_tag :cantidad_stock , nil, readonly: true %>          
  </div>  

   <div class="field">
    <%= f.label :cantidad_a_transferir, "Cantidad a transferir" %><br>
    <%= text_field_tag :cantidad_a_transferir %><br>         
    <input type="button" value="Agregar" class="" id="agregar_bien_a_transferir">       
  </div>    

  <div>
       <%= hidden_field(:bien_de_consumo, :id)  %>
  </div>

  <div class="panel panel-default">
   <div class="panel-heading">Bienes a transferir</div>
  <table id="bienes_table" class="table">
  <thead>
  <tr>            
    <th style="display:none;">Id</th>
    <th style="display:none;">DepoId</th> 
    <th>Codigo</th>
    <th>Nombre</th>
    <th>Deposito</th>
    <th>Cantidad en stock</th>
    <th>Cantidad a transferir</th>    
    <th>Unidad</th>
    <th>Accion</th>
  </tr>
  </thead>
  <tbody>        

  </tbody>    
  </table>  
  </div>  
  <div style="text-align: right;">
    <input type="button" value="Eliminar todos" class="" id="eliminar_todos_los_bienes">     
  </div>

  <div class="field">
    <%= label :area , "Area destino" %><br /> 
    <%= collection_select(:transferencia_area_destino, "area_id", @areas, "id", "nombre", :include_blank => "Seleccione un area...") %>
  </div>

  <div class="field">
    <%= label :deposito, "Deposito destino" %> <br />     
    <%= grouped_collection_select(:transferencia_deposito_destino, :deposito_id, @areas, :depositos, :nombre, :id, :nombre, :include_blank => " Seleccione un deposito...") %>
  </div> 

  <div class="actions">
    <%= f.submit "Aceptar" %>  
  </div>
<% end %>

app/views/transferencias/edit.html.erb
<h1>Editing transferencia</h1>

<%= render 'form' %>

<%= link_to 'Show', @transferencia %> |
<%= link_to 'Back', transferencias_path %>

app/views/transferencias/index.html.erb
<h1>Transferencias realizadas (Directas y por seleccion)</h1>

<table class="table">
  <thead>
    <tr>
      <th>Fecha</th>
      <th>Número</th>
      <th>Area destino</th>
      <th>Deposito destino</th>      
      <th>Origen</th>
      <th>Recepción número</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transferencia.each do |transferencia| %>
      <tr>
        <td><%= transferencia.fecha.strftime("%d/%m/%Y") %></td>
        <td><%= transferencia.id %></td>
        <td><%= transferencia.area ? transferencia.area.nombre : "" %></td>
        <td><%= transferencia.deposito ? transferencia.deposito.nombre : "" %></td>        
        <td><%= transferencia.recepcion_para_transf ? "Desde recepción" : "Manual"  %></td>
        <td><%= transferencia.recepcion_para_transf ? transferencia.recepcion_para_transf.recepcion_de_bien_de_consumo.id : ""  %></td>
        <td><%= link_to 'Ver', transferencia %></td>
        <td><%= link_to 'Imprimir', imprimir_formulario_transferencias_path(transferencia), method: :post, data: { confirm: '¿Esta seguro?' }  %>    
        <td><%= link_to 'Eliminar', transferencia, method: :delete, data: { confirm: '¿Estas seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/transferencias/new.html.erb
<h1>New transferencia</h1>

<%= render 'form' %>

<%= link_to 'Back', transferencias_path %>

app/views/transferencias/nueva_transferencia.html.erb
<h1>Transferencia</h1>

<%= render 'form_nueva_transferencia' %>

<%= link_to 'Volver', transferencias_path %>

app/views/transferencias/nueva_transferencia_desde_recepcion.html.erb
<h1>Transferencia directa</h1>

<%= render 'form' %>

<%= link_to 'Volver', transferencias_path %>

app/views/transferencias/show.html.erb
<h1>Transferencia</h1>

<p>
  <strong>Fecha:</strong>
  <%= @transferencia.fecha.strftime("%d/%m/%Y") %>
</p>

<p>
  <strong>Area destino:</strong>
  <%= @transferencia.area.nombre %>
</p>

<p>
  <strong>Responsable:</strong>
  <%= @transferencia.area.responsable %>
</p>

<p>
  <strong>Deposito destino:</strong>
  <%= @transferencia.deposito.nombre %>
</p>

<div class="panel panel-default">
<div class="panel-heading"> Bienes transferidos </div>
<table class="table">
  <thead>
    <tr>
      <th>Clase</th>
      <th>Nombre</th>
      <th>Codigo</th>
      <th>Cantidad</th>
      <th>Costo</th>
    </tr>
  </thead>
  <tbody>
    <% if @transferencia.bienes_de_consumo_para_transferir.any? %>
        <% @transferencia.bienes_de_consumo_para_transferir.each do |bcc| %>
        <tr>        
          <td><%= bcc.bien_de_consumo.clase.nombre %> </td>
          <td><%= bcc.bien_de_consumo.nombre %> </td>
          <td><%= obtener_codigo_completo_bien_de_consumo(bcc.bien_de_consumo.nombre) %> </td>
          <td><%= bcc.cantidad %> </td>
          <td><%= bcc.costo %> </td>
        </tr>    
        <%end%>
    <% else %>
        <tr>        
          <td></td>
          <td></td>
        </tr>    
    <% end %>      
  </tbody>
</table>
</div>

<%= link_to 'Volver', transferencias_path %>