config/routes.rb
Rails.application.routes.draw do

  resources :ingreso_manual_a_stocks
  get 'reemplazo_clase/index'

  resources :registro_ingreso_manual , only: [:index] do
    collection do
      get 'traer_ingresos_manuales'
    end
  end

  resources :reemplazo_bdc , only: [:index, :new] do
    collection do
      get 'autocomplete_bien_de_consumo_dado_de_baja_nombre_by_clase'
      get 'autocomplete_bien_de_consumo_dado_de_alta_nombre_by_clase'
      post 'traer_item_dado_de_baja_por_nombre'
      post 'traer_item_dado_de_alta_por_nombre'
      post 'traer_bien_dado_de_baja_por_clase'
      post 'traer_bien_dado_de_alta_por_clase'
      post 'crear_reemplazo_de_bien_manual'
    end
  end

  resources :reemplazo_clase , only: [:index, :new] do
    collection do
      get 'autocomplete_clase_dada_de_baja_nombre_por_partida_parcial'
      get 'autocomplete_clase_dada_de_alta_nombre_por_partida_parcial'
      post 'traer_clase_dada_de_baja_por_nombre'
      post 'traer_clase_dada_de_alta_por_nombre'
      post 'traer_clase_dada_de_baja_por_partida_parcial'
      post 'traer_clase_dada_de_alta_por_partida_parcial'
      post 'crear_reemplazo_de_clase_manual'
    end
  end

  resources :foo

  resources :clases do
    collection do
      get 'autocomplete_clase_nombre_traer_todas_las_clases'
      get 'autocomplete_clase_nombre'
      get 'traer_clase_por_id'
      get 'traer_todas_las_clases'
      get 'traer_partidas_parciales_con_codigo_de_clase_existente'
      get 'traer_partidas_parciales_con_nombre_de_clase_similar'
      get 'ver_clases_dadas_de_baja'
      post 'imprimir_listado_de_clases'
    end
  end

  get 'clases/:clase_id/traer_vista_dar_de_baja_y_reemplazar/',
                                to: 'clases#traer_vista_dar_de_baja_y_reemplazar',
                                as: 'traer_vista_dar_de_baja_y_reemplazar_clases'

  put 'clases/:clase_id/dar_de_baja_y_reemplazar/',
                                to: 'clases#dar_de_baja_y_reemplazar',
                                as: 'dar_de_baja_y_reemplazar_clases'

  resources :partidas_parciales do
    collection do
      get 'autocomplete_partida_parcial_nombre'
    end
  end

  resources :partidas_principales

  resources :incisos

  resources :reportes_a_fecha do
    member do
      post 'imprimir_formulario'
    end
    collection do
      get 'traer_items_stock'
    end
  end

  resources :bienes_de_consumo do
    collection do
      get 'autocomplete_bien_de_consumo_nombre_traer_todos_los_items'
      get 'traer_items_de_la_clase'
      get 'traer_item_por_id'
      get 'traer_todos_los_items'
      get 'traer_vista_de_categoria'
      get 'traer_clases_con_codigo_de_bien_existente'
      get 'traer_clases_con_nombre_de_bien_de_consumo_similar'
      get 'ver_items_dados_de_baja'
      get 'existen_stocks_minimos_superados'
      post 'imprimir_listado_de_items'
      post 'traer_costo_de_bien_de_consumo'
    end

    # resources :areas  do
    #   resources :items_stock do
    #     #post 'imprimir_formulario_stock_total_por_bien_y_area'
    #   end
    #end
  end


  get 'bienes_de_consumo/:bien_de_consumo_id/traer_vista_dar_de_baja_y_reemplazar/',
                                to: 'bienes_de_consumo#traer_vista_dar_de_baja_y_reemplazar',
                                as: 'traer_vista_dar_de_baja_y_reemplazar_bienes_de_consumo'

  put 'bienes_de_consumo/:bien_de_consumo_id/dar_de_baja_y_reemplazar_bienes_de_consumo/',
                                to: 'bienes_de_consumo#dar_de_baja_y_reemplazar_bienes_de_consumo',
                                as: 'dar_de_baja_y_reemplazar_bienes_de_consumo'

  resources :personas

  resources :recepciones_de_bien_de_consumo do
      collection do
        get 'ver_rechazadas'
        get 'traer_documentos_con_numero_existente'
      end
      resources :bienes_de_consumo_de_recepcion , only: [:index, :new, :create, :destroy, :show]
  end

  get 'recepciones_de_bien_de_consumo/enviar_a_evaluar/:id',
                                        :to => 'recepciones_de_bien_de_consumo#enviar_a_evaluar',
                                        :as => 'enviar_a_evaluar_recepciones_de_bien_de_consumo'


  post 'bienes_de_consumo_de_recepcion/obtener_nombre_de_bien_de_consumo',
                                        :to => 'bienes_de_consumo_de_recepcion#obtener_nombre_de_bien_de_consumo',
                                        :as => 'obtener_nombre_bien_de_consumo_bienes_de_consumo_de_recepcion'

  post 'bienes_de_consumo_de_recepcion/obtener_codigo_de_bien_de_consumo',
                                        :to => 'bienes_de_consumo_de_recepcion#obtener_codigo_de_bien_de_consumo',
                                        :as => 'obtener_codigo_bien_de_consumo_bienes_de_consumo_de_recepcion'

  delete 'recepciones_de_bien_de_consumo/:recepcion_de_bien_de_consumo_id/eliminar_bien_de_recepcion/:bien_de_consumo_id' => 'recepciones_de_bien_de_consumo#eliminar_bien_de_recepcion',
                                        as: 'eliminar_bienes_de_recepcion_recepciones_de_bien_de_consumo'

  post 'recepciones_de_bien_de_consumo/pegar_campo_descripcion_provisoria', :to => 'recepciones_de_bien_de_consumo#pegar_campo_descripcion_provisoria'

  delete 'recepciones_de_bien_de_consumo/:recepcion_de_bien_de_consumo_id/eliminar_documento_secundario/:documento_secundario_id' => 'recepciones_de_bien_de_consumo#eliminar_documento_secundario',
                                        as: 'eliminar_documento_secundario_recepciones_de_bien_de_consumo'

  resources :transferencias do
    collection do
      get 'nueva_transferencia'
      post 'crear_transferencia'
    end
  end

  get 'transferencias/:recepcion_id/nueva_transferencia_desde_recepcion/',
                                                            to: 'transferencias#nueva_transferencia_desde_recepcion',
                                                            as: 'nueva_transferencia_desde_recepcion_transferencias'

  resources :recepciones_de_bien_de_consumo_en_stock, only: [:index , :show]  do
      get 'imprimir_detalle_recepcion'
      collection do
        get 'autocomplete_documento_principal_nombre'
        get 'traer_recepciones_por_doc_principal'
        get 'ver_recepciones_finalizadas_por_bien_de_consumo_y_fecha'
        get 'traer_recepciones_por_bien_y_fecha'
        get 'ver_recepciones_finalizadas_por_fecha'
        get 'traer_recepciones_finalizadas_por_fecha'
        get 'ver_recepciones_finalizadas_por_fecha_por_recepcion'
        get 'traer_recepciones_finalizadas_por_fecha_por_recepcion'
      end
  end

  get 'recepciones_de_bien_de_consumo_en_stock/documento_principal/:documento_principal/imprimir_formulario_recepciones_por_documento_principal/',
                                                            to: 'recepciones_de_bien_de_consumo_en_stock#imprimir_formulario_recepciones_por_documento_principal',
                                                            as: 'imprimir_formulario_recepciones_por_documento_principal'


  post 'recepciones_de_bien_de_consumo_en_stock/bien_de_consumo/:bien_de_consumo_id/fecha_inicio/:fecha_inicio/fecha_fin/:fecha_fin/imprimir_formulario_recepciones_finalizadas_por_bien_y_fecha/',
                                                            to: 'recepciones_de_bien_de_consumo_en_stock#imprimir_formulario_recepciones_finalizadas_por_bien_y_fecha',
                                                            as: 'imprimir_formulario_recepciones_finalizadas_por_bien_y_fecha'

  post 'recepciones_de_bien_de_consumo_en_stock/fecha_inicio/:fecha_inicio/fecha_fin/:fecha_fin/imprimir_formulario_recepciones_finalizadas_por_fecha/',
                                                            to: 'recepciones_de_bien_de_consumo_en_stock#imprimir_formulario_recepciones_finalizadas_por_fecha',
                                                            as: 'imprimir_formulario_recepciones_finalizadas_por_fecha'

  get 'recepciones_de_bien_de_consumo_en_stock/fecha_inicio/:fecha_inicio/fecha_fin/:fecha_fin/imprimir_formulario_recepciones_finalizadas_por_fecha_por_recepcion/',
                                                            to: 'recepciones_de_bien_de_consumo_en_stock#imprimir_formulario_recepciones_finalizadas_por_fecha_por_recepcion',
                                                            as: 'imprimir_formulario_recepciones_finalizadas_por_fecha_por_recepcion'


  resources :recepciones_de_bien_de_consumo_consumidas, only: [:index , :show]
  resources :depositos
  resources :items_stock , only: [:index, :new ] do
    collection do
      post'ingresar_bienes_a_stock_manualmente'
       get 'guardar_stock_a_fecha'
       get 'traer_todos_los_items_stock'
       get 'traer_items_stock_por_bien_y_area'
       get 'traer_items_stock_por_fecha_bien_y_area_suministro'
       get 'traer_items_stock_minimo_superado'
       get 'traer_items_stock_minimo_superado_por_bien_y_area'
       get 'traer_datos_de_clase_y_bien'
       get 'ver_stock_minimo_superado'
       get 'ver_stock_con_subtotal_por_pp'
       get 'autocomplete_bien_de_consumo_nombre'
       get 'autocomplete_area_nombre'
       post 'imprimir_formulario_stock_total_todos_los_bienes'
      post 'traer_cantidad_en_stock_en_suministro'
      post 'imprimir_formulario_stock_faltante'
     end
  end



  post 'items_stock/area_id/(:area_id)/bien_id/(:bien_id)/partida_parcial/(:partida_parcial)/fecha_inicio/(:fecha_inicio)/fecha_fin/(:fecha_fin)/imprimir_formulario_stock_total_por_bien_y_area/',
                                                            to: 'items_stock#imprimir_formulario_stock_total_por_bien_y_area',
                                                            as: 'imprimir_formulario_stock_total_por_bien_y_area'

  post 'items_stock/area_id/(:area_id)/bien_id/(:bien_id)/imprimir_formulario_stock_faltante/',
                                                            to: 'items_stock#imprimir_formulario_stock_faltante',

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>  
  <div id="error_explanation">
    <div class="alert alert-error">
      El formulario contiene <%= pluralize(@user.errors.count, "error/es") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li> <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_form_arbol_bienes.erb
	<div class="field">	
	<%= label_tag :clase, "Clase" %><br>
 	<%= collection_select(:categoria, "clase_id", @clases, "id", "combinar_codigo_nombre", :include_blank => "Seleccione...") %> 
 		    		   				   
	</div>  	

	<div class="field">			
		<%= label_tag :bien_de_consumo, "Bien de consumo" %><br>
	  <%= grouped_collection_select(:categoria, :bien_de_consumo_id, @clases, :bienes_de_consumo, "combinar_codigo_nombre", :id, :nombre, :include_blank => " Seleccione...") %>
	</div>

app/views/shared/_form_arbol_bienes_old.erb
	<div class="field">	
		<%= label_tag :inciso %><br>
	 	<%= collection_select(:categoria, "inciso_id", @incisos, "id", "nombre", :include_blank => "Seleccione...") %>   	
	</div> 

	<div class="field">			
	  <%= label_tag :partida_principal, "Partida principal" %><br>
	  <%= grouped_collection_select(:categoria, :partida_principal_id, @incisos, :partidas_principales, :nombre, :id, :nombre, :include_blank => " Seleccione...") %>
	</div> 

	<div class="field">			
	  <%= label_tag :partida_parcial, "Partida parcial" %><br>
	  <%= grouped_collection_select(:categoria, :partida_parcial_id, @partidas_principales, :partidas_parciales, :nombre, :id, :nombre, :include_blank => " Seleccione...") %>  
	</div> 

	<div class="field">	
		<%= label_tag :clase, "Clase" %><br>
	  <%= grouped_collection_select(:categoria, :clase_id, @partidas_parciales, :clases, :nombre, :id, :nombre, :include_blank => " Seleccione...") %>  
	</div>  

	<div class="field">			
		<%= label_tag :bien_de_consumo, "Bien de consumo" %><br>
	  <%= grouped_collection_select(:categoria, :bien_de_consumo_id, @clases, :bienes_de_consumo, :nombre, :id, :nombre, :include_blank => " Seleccione...") %>
	</div>

app/views/shared/_form_show.html.erb
<p>
  <strong>Recepcion numero:</strong>
  <%= @recepcion_de_bien_de_consumo.id %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @recepcion_de_bien_de_consumo.fecha.strftime("%d/%m/%Y") %>
</p>

<p>
  <strong>Estado:</strong>
  <%= RecepcionDeBienDeConsumo::ESTADOS.key(@recepcion_de_bien_de_consumo.estado)%>
</p>

<% if !@recepcion_de_bien_de_consumo.descripcion_provisoria %>
  <p>
  <strong>Descripcion provisoria:</strong>
  <%= @recepcion_de_bien_de_consumo.descripcion_provisoria %>
  </p>    
<% end %>
</br>
<div class="panel panel-default">
   <div class="panel-heading">Documento principal</div>
<table class="table">
  <thead>
    <tr>
      <th>Tipo</th>
      <th>numero</th>
    </tr>
  </thead>
  <tbody>    
      <tr>      	
        <td><%= @recepcion_de_bien_de_consumo.documento_principal.documento_de_recepcion.tipo_de_documento.nombre %></td>
        <td><%= @recepcion_de_bien_de_consumo.documento_principal.documento_de_recepcion.numero_de_documento %></td>
      </tr>    
  </tbody>
</table>
</div>

  <div class="panel panel-default">
   <div class="panel-heading">Documentos secundarios</div>
<table class="table">
  <thead>
    <tr>
      <th>Tipo</th>
      <th>numero</th>
    </tr>
  </thead>
  <tbody>
  	<% if @recepcion_de_bien_de_consumo.documentos_secundario.any? %>
        <% @recepcion_de_bien_de_consumo.documentos_secundario.each do |doc_secundario| %>
        <% if doc_secundario.documento_de_recepcion %>
      	     <tr>      	          
        	     <td><%= doc_secundario.documento_de_recepcion.tipo_de_documento.nombre %> </td>
        	     <td><%= doc_secundario.documento_de_recepcion.numero_de_documento %> </td>        
      	     </tr>    
        <% end %>
    <%end%>
    <% else %>
      	<tr>      	
        	<td></td>
        	<td></td>
      	</tr>    
   	<% end %>      
  </tbody>
</table>
</div>

<div class="panel panel-default">
<div class="panel-heading">Bienes de consumo</div>
<table class="table">
  <thead>
    <tr>
      <th>Clase</th>
      <th>Nombre</th>
      <th>Codigo</th>
      <th>Cantidad</th>
      <th>Costo</th>
      <th>Costo total</th>
      <th>Descripción</th>
    </tr>
  </thead>
  <tbody>
    <% if @recepcion_de_bien_de_consumo.bienes_de_consumo_de_recepcion.any? %>
        <% @recepcion_de_bien_de_consumo.bienes_de_consumo_de_recepcion.each do |bcr| %>
        <tr>              
          <td><%= bcr.bien_de_consumo.clase.nombre %> </td>
          <td><%= bcr.bien_de_consumo.nombre %> </td>
          <td><%= obtener_codigo_completo_bien_de_consumo(bcr.bien_de_consumo.nombre) %> </td>
          <td><%= bcr.cantidad %> </td>
          <td><%= number_to_currency(bcr.costo, precision: 3) %> </td>
          <td><%= obtener_costo_total(bcr.cantidad, bcr.costo) %> </td> 
          <td><%= bcr.descripcion %> </td>
        </tr>              
        <%end%>
    <% else %>
        <tr>        
          <td></td>
          <td></td>
        </tr>    
    <% end %>      
  </tbody>
</table>  
</div>
<div  style="text-align:right;">
    <%= label_tag :total_general, "Costo total general: " %>
    <%= obtener_total_general_de_bienes_de_consumo(@recepcion_de_bien_de_consumo.bienes_de_consumo_de_recepcion)%>
</div>
<br />
  <div>
    <td><%= link_to 'Imprimir', recepciones_de_bien_de_consumo_en_stock_imprimir_detalle_recepcion_path(@recepcion_de_bien_de_consumo.id) %></td>
  </div>