config/routes.rb
Rails.application.routes.draw do

  resources :ingreso_manual_a_stocks
  get 'reemplazo_clase/index'

  resources :registro_ingreso_manual , only: [:index] do
    collection do
      get 'traer_ingresos_manuales'
    end
  end

  resources :reemplazo_bdc , only: [:index, :new] do
    collection do
      get 'autocomplete_bien_de_consumo_dado_de_baja_nombre_by_clase'
      get 'autocomplete_bien_de_consumo_dado_de_alta_nombre_by_clase'
      post 'traer_item_dado_de_baja_por_nombre'
      post 'traer_item_dado_de_alta_por_nombre'
      post 'traer_bien_dado_de_baja_por_clase'
      post 'traer_bien_dado_de_alta_por_clase'
      post 'crear_reemplazo_de_bien_manual'
    end
  end

  resources :reemplazo_clase , only: [:index, :new] do
    collection do
      get 'autocomplete_clase_dada_de_baja_nombre_por_partida_parcial'
      get 'autocomplete_clase_dada_de_alta_nombre_por_partida_parcial'
      post 'traer_clase_dada_de_baja_por_nombre'
      post 'traer_clase_dada_de_alta_por_nombre'
      post 'traer_clase_dada_de_baja_por_partida_parcial'
      post 'traer_clase_dada_de_alta_por_partida_parcial'
      post 'crear_reemplazo_de_clase_manual'
    end
  end

  resources :foo

  resources :clases do
    collection do
      get 'autocomplete_clase_nombre_traer_todas_las_clases'
      get 'autocomplete_clase_nombre'
      get 'traer_clase_por_id'
      get 'traer_todas_las_clases'
      get 'traer_partidas_parciales_con_codigo_de_clase_existente'
      get 'traer_partidas_parciales_con_nombre_de_clase_similar'
      get 'ver_clases_dadas_de_baja'
      post 'imprimir_listado_de_clases'
    end
  end

  get 'clases/:clase_id/traer_vista_dar_de_baja_y_reemplazar/',
                                to: 'clases#traer_vista_dar_de_baja_y_reemplazar',
                                as: 'traer_vista_dar_de_baja_y_reemplazar_clases'

  put 'clases/:clase_id/dar_de_baja_y_reemplazar/',
                                to: 'clases#dar_de_baja_y_reemplazar',
                                as: 'dar_de_baja_y_reemplazar_clases'

  resources :partidas_parciales do
    collection do
      get 'autocomplete_partida_parcial_nombre'
    end
  end

  resources :partidas_principales

  resources :incisos

  resources :reportes_a_fecha do
    member do
      post 'imprimir_formulario'
    end
    collection do
      get 'traer_items_stock'
    end
  end

  resources :bienes_de_consumo do
    collection do
      get 'autocomplete_bien_de_consumo_nombre_traer_todos_los_items'
      get 'traer_items_de_la_clase'
      get 'traer_item_por_id'
      get 'traer_todos_los_items'
      get 'traer_vista_de_categoria'
      get 'traer_clases_con_codigo_de_bien_existente'
      get 'traer_clases_con_nombre_de_bien_de_consumo_similar'
      get 'ver_items_dados_de_baja'
      get 'existen_stocks_minimos_superados'
      post 'imprimir_listado_de_items'
      post 'traer_costo_de_bien_de_consumo'
    end

    # resources :areas  do
    #   resources :items_stock do
    #     #post 'imprimir_formulario_stock_total_por_bien_y_area'
    #   end
    #end
  end


  get 'bienes_de_consumo/:bien_de_consumo_id/traer_vista_dar_de_baja_y_reemplazar/',
                                to: 'bienes_de_consumo#traer_vista_dar_de_baja_y_reemplazar',
                                as: 'traer_vista_dar_de_baja_y_reemplazar_bienes_de_consumo'

  put 'bienes_de_consumo/:bien_de_consumo_id/dar_de_baja_y_reemplazar_bienes_de_consumo/',
                                to: 'bienes_de_consumo#dar_de_baja_y_reemplazar_bienes_de_consumo',
                                as: 'dar_de_baja_y_reemplazar_bienes_de_consumo'

  resources :personas

  resources :recepciones_de_bien_de_consumo do
      collection do
        get 'ver_rechazadas'
        get 'traer_documentos_con_numero_existente'
      end
      resources :bienes_de_consumo_de_recepcion , only: [:index, :new, :create, :destroy, :show]
  end

  get 'recepciones_de_bien_de_consumo/enviar_a_evaluar/:id',
                                        :to => 'recepciones_de_bien_de_consumo#enviar_a_evaluar',
                                        :as => 'enviar_a_evaluar_recepciones_de_bien_de_consumo'


  post 'bienes_de_consumo_de_recepcion/obtener_nombre_de_bien_de_consumo',
                                        :to => 'bienes_de_consumo_de_recepcion#obtener_nombre_de_bien_de_consumo',
                                        :as => 'obtener_nombre_bien_de_consumo_bienes_de_consumo_de_recepcion'

  post 'bienes_de_consumo_de_recepcion/obtener_codigo_de_bien_de_consumo',
                                        :to => 'bienes_de_consumo_de_recepcion#obtener_codigo_de_bien_de_consumo',
                                        :as => 'obtener_codigo_bien_de_consumo_bienes_de_consumo_de_recepcion'

  delete 'recepciones_de_bien_de_consumo/:recepcion_de_bien_de_consumo_id/eliminar_bien_de_recepcion/:bien_de_consumo_id' => 'recepciones_de_bien_de_consumo#eliminar_bien_de_recepcion',
                                        as: 'eliminar_bienes_de_recepcion_recepciones_de_bien_de_consumo'

  post 'recepciones_de_bien_de_consumo/pegar_campo_descripcion_provisoria', :to => 'recepciones_de_bien_de_consumo#pegar_campo_descripcion_provisoria'

  delete 'recepciones_de_bien_de_consumo/:recepcion_de_bien_de_consumo_id/eliminar_documento_secundario/:documento_secundario_id' => 'recepciones_de_bien_de_consumo#eliminar_documento_secundario',
                                        as: 'eliminar_documento_secundario_recepciones_de_bien_de_consumo'

  resources :transferencias do
    collection do
      get 'nueva_transferencia'
      post 'crear_transferencia'
    end
  end

  get 'transferencias/:recepcion_id/nueva_transferencia_desde_recepcion/',
                                                            to: 'transferencias#nueva_transferencia_desde_recepcion',
                                                            as: 'nueva_transferencia_desde_recepcion_transferencias'

  resources :recepciones_de_bien_de_consumo_en_stock, only: [:index , :show]  do
      get 'imprimir_detalle_recepcion'
      collection do
        get 'autocomplete_documento_principal_nombre'
        get 'traer_recepciones_por_doc_principal'
        get 'ver_recepciones_finalizadas_por_bien_de_consumo_y_fecha'
        get 'traer_recepciones_por_bien_y_fecha'
        get 'ver_recepciones_finalizadas_por_fecha'
        get 'traer_recepciones_finalizadas_por_fecha'
        get 'ver_recepciones_finalizadas_por_fecha_por_recepcion'
        get 'traer_recepciones_finalizadas_por_fecha_por_recepcion'
      end
  end

  get 'recepciones_de_bien_de_consumo_en_stock/documento_principal/:documento_principal/imprimir_formulario_recepciones_por_documento_principal/',
                                                            to: 'recepciones_de_bien_de_consumo_en_stock#imprimir_formulario_recepciones_por_documento_principal',
                                                            as: 'imprimir_formulario_recepciones_por_documento_principal'


  post 'recepciones_de_bien_de_consumo_en_stock/bien_de_consumo/:bien_de_consumo_id/fecha_inicio/:fecha_inicio/fecha_fin/:fecha_fin/imprimir_formulario_recepciones_finalizadas_por_bien_y_fecha/',
                                                            to: 'recepciones_de_bien_de_consumo_en_stock#imprimir_formulario_recepciones_finalizadas_por_bien_y_fecha',
                                                            as: 'imprimir_formulario_recepciones_finalizadas_por_bien_y_fecha'

  post 'recepciones_de_bien_de_consumo_en_stock/fecha_inicio/:fecha_inicio/fecha_fin/:fecha_fin/imprimir_formulario_recepciones_finalizadas_por_fecha/',
                                                            to: 'recepciones_de_bien_de_consumo_en_stock#imprimir_formulario_recepciones_finalizadas_por_fecha',
                                                            as: 'imprimir_formulario_recepciones_finalizadas_por_fecha'

  get 'recepciones_de_bien_de_consumo_en_stock/fecha_inicio/:fecha_inicio/fecha_fin/:fecha_fin/imprimir_formulario_recepciones_finalizadas_por_fecha_por_recepcion/',
                                                            to: 'recepciones_de_bien_de_consumo_en_stock#imprimir_formulario_recepciones_finalizadas_por_fecha_por_recepcion',
                                                            as: 'imprimir_formulario_recepciones_finalizadas_por_fecha_por_recepcion'


  resources :recepciones_de_bien_de_consumo_consumidas, only: [:index , :show]
  resources :depositos
  resources :items_stock , only: [:index, :new ] do
    collection do
      post'ingresar_bienes_a_stock_manualmente'
       get 'guardar_stock_a_fecha'
       get 'traer_todos_los_items_stock'
       get 'traer_items_stock_por_bien_y_area'
       get 'traer_items_stock_por_fecha_bien_y_area_suministro'
       get 'traer_items_stock_minimo_superado'
       get 'traer_items_stock_minimo_superado_por_bien_y_area'
       get 'traer_datos_de_clase_y_bien'
       get 'ver_stock_minimo_superado'
       get 'ver_stock_con_subtotal_por_pp'
       get 'autocomplete_bien_de_consumo_nombre'
       get 'autocomplete_area_nombre'
       post 'imprimir_formulario_stock_total_todos_los_bienes'
      post 'traer_cantidad_en_stock_en_suministro'
      post 'imprimir_formulario_stock_faltante'
     end
  end



  post 'items_stock/area_id/(:area_id)/bien_id/(:bien_id)/partida_parcial/(:partida_parcial)/fecha_inicio/(:fecha_inicio)/fecha_fin/(:fecha_fin)/imprimir_formulario_stock_total_por_bien_y_area/',
                                                            to: 'items_stock#imprimir_formulario_stock_total_por_bien_y_area',
                                                            as: 'imprimir_formulario_stock_total_por_bien_y_area'

  post 'items_stock/area_id/(:area_id)/bien_id/(:bien_id)/imprimir_formulario_stock_faltante/',
                                                            to: 'items_stock#imprimir_formulario_stock_faltante',

app/views/items_stock/_deposito.html.erb
   <div class="field_descripcion_provisoria">
     <%= deposito.text_field :nombre %>
   </div>

app/views/items_stock/_form.html.erb
<%= form_for(@item_stock, url: ingresar_bienes_a_stock_manualmente_items_stock_path, html: { method: "post" }) do |f| %>
  <% if @item_stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item_stock.errors.count, "error/es") %> impide/n ingresar el item a stock:</h2>
      <ul>
      <% @item_stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>       
  <% end %>
  
<div class="row">
  <div class="col-md-3">      
      <h3> Buscar por nombre </h3>   
      <div class="field">
           <%= f.label :nombre%><br>  
        </div>   
        <div class="field">
            <%= autocomplete_field_tag 'bien_de_consumo_nombre', "", autocomplete_bien_de_consumo_nombre_items_stock_path , :size => 75, :update_elements => {} %>
        </div>  
        <div class="field">
          <%= f.hidden_field :bien_de_consumo_id %>
        </div> 
    </div>  

    <div class="col-md-3">        
      <h3> Seleccionar arbol </h3>            
        <div class="field"> 
        <%= label_tag :clase, "Clase" %><br>
        <%= collection_select(:categoria, "clase_id", Clase.joins(:partida_parcial => [:partida_principal]).where("clases.fecha_de_baja IS NULL").order("partidas_principales.codigo").order("partidas_parciales.codigo").order("clases.codigo"), "id", "combinar_codigo_nombre", :include_blank => "Seleccione...") %> 
             
        </div>    
        <div class="field">     
          <%= label_tag :bien_de_consumo, "Bien de consumo" %><br>
          <%= grouped_collection_select(:items_stock, :bien_de_consumo_id, Clase.joins(:partida_parcial => [:partida_principal]).where("clases.fecha_de_baja IS NULL").order("partidas_principales.codigo").order("partidas_parciales.codigo").order("clases.codigo"), :bienes_de_consumo, :nombre, :id, :nombre, :include_blank => " Seleccione...") %>
        </div>
    </div>      
  </div>        

  <div class="field">
    <%= f.label :cantidad_en_stock, "Cantidad en stock" %><br>
    <%= text_field_tag :cantidad_en_stock, nil , :disabled => true, :class=> "uneditable-input" %>   
  </div>  

  <div class="field">
    <%= f.label :cantidad, "Cantidad nueva en stock" %><br>
    <%= f.text_field :cantidad  %>          
  </div>  

  <div class="field">
    <%= f.label :costo_actual, "Costo actual" %><br>
    <%= text_field_tag :costo_actual, nil,  :disabled => true, :class=> "uneditable-input" %>        
  </div>  

  <div class="field">
    <%= f.label :costo, "Costo nuevo" %><br>
    <%= text_field_tag :costo , nil %>          
  </div>  

  <div class="actions">
    <%= f.submit "Aceptar" %> 
  </div>

<% end %>

app/views/items_stock/_form_tabla_stock.html.erb
<% if !@items_stock.nil? && @items_stock.length > 0 %>
  <table class="table">
    <thead>
      <tr>
        <th>Clase</th>
        <th>Codigo</th>
        <th>Nombre</th>
        <th style="text-align: right">Cantidad</th>
        <th style="text-align: right">Costo</th>
        <th style="text-align: right">Costo total</th>
        <th>Deposito</th>
      </tr>
    </thead>
    <tbody>
      <% @items_stock.each do |item_stock| %>
        <tr>
          <td><%= item_stock.bien_de_consumo.clase.nombre %></td>
          <td><%= obtener_codigo_completo_bien_de_consumo(item_stock.bien_de_consumo.nombre) %></td>
          <td><%= item_stock.bien_de_consumo.nombre %></td>
          <td style="text-align: right"><%= item_stock.cantidad.to_i %></td>
          <td style="text-align: right"><%= number_to_currency(item_stock.costo_de_bien_de_consumo.costo, :precision => 3) %></td>
          <td style="text-align: right"><%= number_to_currency(obtener_costo_total(item_stock.costo_de_bien_de_consumo.costo, item_stock.cantidad), precision: 3)  %></td>
          <td><%= item_stock.deposito.nombre %></td>
        </tr>
      <% end %>
        <% if(@items_stock.length > 0) %>
          <td>
            <%= link_to 'Imprimir', imprimir_formulario_stock_total_por_bien_y_area_path(@items_stock[0].area_id_impresion, @items_stock[0].bien_id_impresion,  @items_stock[0].partida_parcial_impresion, @items_stock[0].fecha_inicio_impresion, @items_stock[0].fecha_fin_impresion), method: :post, data: { confirm: '¿Esta seguro?' }  %>
        </td>
        <!-- <% if @items_stock[0].bien_id_impresion.blank? && @items_stock[0].partida_parcial_impresion.blank? %>
          <td>
            <%= link_to 'Imprimir', imprimir_formulario_stock_total_todos_los_bienes_items_stock_path , method: :post, data: { confirm: '¿Esta seguro?' }  %>
          </td>
        <% else  %>
            <td>
              <%= link_to 'Imprimir', imprimir_formulario_stock_total_por_bien_y_area_path(@items_stock[0].area_id_impresion, @items_stock[0].bien_id_impresion,  @items_stock[0].partida_parcial_impresion, @items_stock[0].fecha_inicio_impresion, @items_stock[0].fecha_fin_impresion), method: :post, data: { confirm: '¿Esta seguro?' }  %>
            </td>
        <% end %> -->
      <% end %>
    </tbody>
  </table>
    <tr>
      <div  style="text-align:right;">
        <%= label_tag :total_general, "Costo total general: " %>
        <%= @costo_total_general %>
      </div>
    </tr>
     <%= will_paginate(@items_stock, :params => { :controller => "items_stock", :action => @action_destino }, renderer: BootstrapPagination::Rails) %>
<% end %>

app/views/items_stock/_form_tabla_stock_con_subtotal_por_pp.html.erb
<% if !@items_stock.nil? && @items_stock.length > 0 %>
  <table class="table">
    <thead>
      <tr>
        <th>Clase</th>
        <th>Codigo</th>
        <th>Nombre</th>
        <th style="text-align: right">Cantidad</th>
        <th style="text-align: right">Costo</th>
        <th style="text-align: right">Costo total</th>
        <th>Deposito</th>
      </tr>
    </thead>
    <tbody>
      <% @items_stock.each do |item_stock| %>
        <tr>
          <td><%= item_stock.bien_de_consumo.clase.nombre %></td>
          <td><%= obtener_codigo_completo_bien_de_consumo(item_stock.bien_de_consumo.nombre) %></td>
          <td><%= item_stock.bien_de_consumo.nombre %></td>
          <td style="text-align: right"><%= item_stock.cantidad.to_i %></td>
          <td style="text-align: right"><%= number_to_currency(item_stock.traer_ultimo_costo_de_bien_de_consumo, :precision => 3) %></td>
          <td style="text-align: right"><%= number_to_currency(obtener_costo_total(item_stock.traer_ultimo_costo_de_bien_de_consumo, item_stock.cantidad), precision: 3)  %></td>
          <td><%= item_stock.deposito.nombre %></td>
        </tr>
        <% unless item_stock.subtotal.nil? %>
          <tr>
              <td colspan="6"></td>
              <td style="text-align: right"> <strong> Subtotal: </strong> </td>
              <td style="text-align: right"> <strong> <%=  number_to_currency(item_stock.subtotal, precision: 3) %> </strong> </td>
          </tr>
          <tr>
            <td>
              </br>
            </td>
          </tr>
        <% end %>
      <% end %>
    <% if(@items_stock.length > 0) %>
          <td>
            <%= link_to 'Imprimir', imprimir_formulario_stock_total_con_subtotal_por_pp_path, method: :post, data: { confirm: '¿Esta seguro?' }  %>
        </td>
    <% end %>
    </tbody>
  </table>
    <tr>
      <div  style="text-align:right;">
        <%= label_tag :total_general, "Costo total general: " %>
        <%= @costo_total_general %>
      </div>
    </tr>
      <%= will_paginate(@items_stock, :params => { :controller => "items_stock", :action => @action_destino }, renderer: BootstrapPagination::Rails) %>
<% end %>

app/views/items_stock/_form_tabla_stock_minimo_superado.html.erb
<% if !@items_stock.nil? && @items_stock.length > 0 %>
  <table class="table">
    <thead>
      <tr>
        <th>Clase</th>
        <th>Codigo</th>
        <th>Nombre</th>
        <th style="text-align: right">Cantidad</th>
        <th style="text-align: right">Costo</th>
        <th style="text-align: right">Costo total</th>
        <th>Deposito</th>
      </tr>
    </thead>
    <tbody>
      <% @items_stock.each do |item_stock| %>
        <tr>
          <td><%= item_stock.bien_de_consumo.clase.nombre %></td>
          <td><%= obtener_codigo_completo_bien_de_consumo(item_stock.bien_de_consumo.nombre) %></td>
          <td><%= item_stock.bien_de_consumo.nombre %></td>
          <td style="text-align: right"><%= item_stock.cantidad.to_i %></td>
          <td style="text-align: right"><%= number_to_currency(item_stock.costo_de_bien_de_consumo.costo, :precision => 3) %></td>
          <td style="text-align: right"><%= number_to_currency(obtener_costo_total(item_stock.costo_de_bien_de_consumo.costo, item_stock.cantidad), precision: 3)  %></td>
          <td><%= item_stock.deposito.nombre %></td>
        </tr>
      <% end %>
      <% if(@items_stock.length > 0) %>
          <td><%= link_to 'Imprimir', imprimir_formulario_stock_faltante_path(@items_stock[0].area_id_impresion, @items_stock[0].bien_id_impresion) , method: :post, data: { confirm: '¿Esta seguro?' }  %>
          </td>
      <% end %>
    </tbody>
  </table>
    <tr>
      <div  style="text-align:right;">
        <%= label_tag :total_general, "Costo total general: " %>
        <%= @costo_total_general %>
      </div>
    </tr>
      <%= will_paginate(@items_stock, :params => { :controller => "items_stock" }, renderer: BootstrapPagination::Rails) %>
      <% end %>

app/views/items_stock/create.html.erb
<h1>ItemStock#create</h1>
<p>Find me in app/views/item_stock/create.html.erb</p>

app/views/items_stock/traer_items_stock_minimo_superado.js.erb
"<%= escape_javascript(render(:partial => "form_tabla_stock_minimo_superado")) %>"

app/views/items_stock/traer_items_stock_por_bien.js.erb
"<%= escape_javascript(render(:partial => "form_tabla_stock")) %>"

app/views/items_stock/traer_items_stock_por_fecha_bien_y_area_suministro.js.erb
"<%= escape_javascript(render(:partial => "form_tabla_stock")) %>"

app/views/items_stock/traer_stock_total_con_subtotal_por_pp.js.erb
"<%= escape_javascript(render(:partial => "form_tabla_stock_con_subtotal_por_pp")) %>"

app/views/items_stock/traer_todos_los_items_stock.js.erb
"<%= escape_javascript(render(:partial => "form_tabla_stock")) %>"

app/views/items_stock/ver_ingresar_a_stock.html.erb
<h1>Ingresar a stock</h1>

<%= render 'form' %>

<%= link_to 'Volver', items_stock_path %>

app/views/items_stock/ver_stock_con_subtotal_por_pp.html.erb
<h1>Stock de bienes de consumo con subtotal por partida parcial </h1>

<div class="row">
  <br />
  <div class="span6 offset3">
  <div>

  </div>

  <div id="tabla_items">
    <%= render 'form_tabla_stock_con_subtotal_por_pp' %>
  </div>

</div>

app/views/items_stock/ver_stock_minimo_superado.html.erb
<h1> Items con stock mínimo superado </h1>

<div class="row">
  <br />
  <div class="span6 offset3">
  <div>
    <div class="field">
      <%= label_tag 'Bien de consumo' %>
    </div>
    <div class="field">
      <%= autocomplete_field_tag 'bien_de_consumo_nombre', '', autocomplete_bien_de_consumo_nombre_items_stock_path , :size => 75, :update_elements => {} %>
    </div>

    <div class="field">
      <%= label_tag 'Area' %>
    </div>
    <div class="field">
      <%= autocomplete_field_tag 'area_nombre', '', autocomplete_area_nombre_items_stock_path , :size => 75 %>
    </div>

    <input type="button" value="Buscar" id="traer_items_stock_minimo_por_bien_de_consumo_y_area">
    <input type="button" value="Traer todos" id="traer_todos_los_items_stock_con_stock_minimo_superado">

    <%= hidden_field_tag 'bien_de_consumo_id' %>

    <%= hidden_field_tag 'area_id' %>
  </div>

  <div id="tabla_items">
    <%= render 'form_tabla_stock_minimo_superado' %>
  </div>

</div>